
<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
 
class CityTableSeeder2 extends Seeder {

    public function run()
    {
         
        $cities = [
                        [ 'id' => 9987, 'name'=>"Diapaga", 'state_id'=> 609],
                        [ 'id' => 9988, 'name'=>"Kantchari", 'state_id'=> 609],
                        [ 'id' => 9989, 'name'=>"Hounde", 'state_id'=> 610],
                        [ 'id' => 9990, 'name'=>"Ouahigouya", 'state_id'=> 611],
                        [ 'id' => 9991, 'name'=>"Gourcy", 'state_id'=> 612],
                        [ 'id' => 9992, 'name'=>"Manga", 'state_id'=> 613],
                        [ 'id' => 9993, 'name'=>"Bubanza", 'state_id'=> 614],
                        [ 'id' => 9994, 'name'=>"Bujumbura", 'state_id'=> 615],
                        [ 'id' => 9995, 'name'=>"Bururi", 'state_id'=> 616],
                        [ 'id' => 9996, 'name'=>"Cankuzo", 'state_id'=> 617],
                        [ 'id' => 9997, 'name'=>"Cibitoke", 'state_id'=> 618],
                        [ 'id' => 9998, 'name'=>"Gitega", 'state_id'=> 619],
                        [ 'id' => 9999, 'name'=>"Karuzi", 'state_id'=> 620],
                        [ 'id' => 10000, 'name'=>"Kayanza", 'state_id'=> 621],
                        [ 'id' => 10001, 'name'=>"Kirundo", 'state_id'=> 622],
                        [ 'id' => 10002, 'name'=>"Makamba", 'state_id'=> 623],
                        [ 'id' => 10003, 'name'=>"Muramvya", 'state_id'=> 624],
                        [ 'id' => 10004, 'name'=>"Muyinga", 'state_id'=> 625],
                        [ 'id' => 10005, 'name'=>"Ngozi", 'state_id'=> 626],
                        [ 'id' => 10006, 'name'=>"Rutana", 'state_id'=> 627],
                        [ 'id' => 10007, 'name'=>"Ruyigi", 'state_id'=> 628],
                        [ 'id' => 10008, 'name'=>"Kampot", 'state_id'=> 635],
                        [ 'id' => 10009, 'name'=>"Ta Khmau", 'state_id'=> 636],
                        [ 'id' => 10010, 'name'=>"Kracheh", 'state_id'=> 638],
                        [ 'id' => 10011, 'name'=>"Pousat", 'state_id'=> 645],
                        [ 'id' => 10012, 'name'=>"Phumi Takaev", 'state_id'=> 652],
                        [ 'id' => 10013, 'name'=>"Banyo", 'state_id'=> 653],
                        [ 'id' => 10014, 'name'=>"Meiganga", 'state_id'=> 653],
                        [ 'id' => 10015, 'name'=>"Ngaoundere", 'state_id'=> 653],
                        [ 'id' => 10016, 'name'=>"Tibati", 'state_id'=> 653],
                        [ 'id' => 10017, 'name'=>"Tignere", 'state_id'=> 653],
                        [ 'id' => 10018, 'name'=>"Akonolinga", 'state_id'=> 654],
                        [ 'id' => 10019, 'name'=>"Bafia", 'state_id'=> 654],
                        [ 'id' => 10020, 'name'=>"Eseka", 'state_id'=> 654],
                        [ 'id' => 10021, 'name'=>"Mbalmayo", 'state_id'=> 654],
                        [ 'id' => 10022, 'name'=>"Mfou", 'state_id'=> 654],
                        [ 'id' => 10023, 'name'=>"Monatele", 'state_id'=> 654],
                        [ 'id' => 10024, 'name'=>"Nanga Eboko", 'state_id'=> 654],
                        [ 'id' => 10025, 'name'=>"Obala", 'state_id'=> 654],
                        [ 'id' => 10026, 'name'=>"Ombesa", 'state_id'=> 654],
                        [ 'id' => 10027, 'name'=>"Saa", 'state_id'=> 654],
                        [ 'id' => 10028, 'name'=>"Yaounde", 'state_id'=> 654],
                        [ 'id' => 10029, 'name'=>"Abong Mbang", 'state_id'=> 655],
                        [ 'id' => 10030, 'name'=>"Batouri", 'state_id'=> 655],
                        [ 'id' => 10031, 'name'=>"Bertoua", 'state_id'=> 655],
                        [ 'id' => 10032, 'name'=>"Betare Oya", 'state_id'=> 655],
                        [ 'id' => 10033, 'name'=>"Djoum", 'state_id'=> 655],
                        [ 'id' => 10034, 'name'=>"Doume", 'state_id'=> 655],
                        [ 'id' => 10035, 'name'=>"Lomie", 'state_id'=> 655],
                        [ 'id' => 10036, 'name'=>"Yokadouma", 'state_id'=> 655],
                        [ 'id' => 10037, 'name'=>"Bonaberi", 'state_id'=> 656],
                        [ 'id' => 10038, 'name'=>"Dibombari", 'state_id'=> 656],
                        [ 'id' => 10039, 'name'=>"Douala", 'state_id'=> 656],
                        [ 'id' => 10040, 'name'=>"Edea", 'state_id'=> 656],
                        [ 'id' => 10041, 'name'=>"Loum", 'state_id'=> 656],
                        [ 'id' => 10042, 'name'=>"Manjo", 'state_id'=> 656],
                        [ 'id' => 10043, 'name'=>"Mbanga", 'state_id'=> 656],
                        [ 'id' => 10044, 'name'=>"Nkongsamba", 'state_id'=> 656],
                        [ 'id' => 10045, 'name'=>"Yabassi", 'state_id'=> 656],
                        [ 'id' => 10046, 'name'=>"Figuif", 'state_id'=> 657],
                        [ 'id' => 10047, 'name'=>"Garoua", 'state_id'=> 657],
                        [ 'id' => 10048, 'name'=>"Guider", 'state_id'=> 657],
                        [ 'id' => 10049, 'name'=>"Lagdo", 'state_id'=> 657],
                        [ 'id' => 10050, 'name'=>"Poli", 'state_id'=> 657],
                        [ 'id' => 10051, 'name'=>"Rey Bouba", 'state_id'=> 657],
                        [ 'id' => 10052, 'name'=>"Tchollire", 'state_id'=> 657],
                        [ 'id' => 10053, 'name'=>"Figuif", 'state_id'=> 658],
                        [ 'id' => 10054, 'name'=>"Garoua", 'state_id'=> 658],
                        [ 'id' => 10055, 'name'=>"Guider", 'state_id'=> 658],
                        [ 'id' => 10056, 'name'=>"Lagdo", 'state_id'=> 658],
                        [ 'id' => 10057, 'name'=>"Poli", 'state_id'=> 658],
                        [ 'id' => 10058, 'name'=>"Rey Bouba", 'state_id'=> 658],
                        [ 'id' => 10059, 'name'=>"Tchollire", 'state_id'=> 658],
                        [ 'id' => 10060, 'name'=>"Bamenda", 'state_id'=> 659],
                        [ 'id' => 10061, 'name'=>"Kumbo", 'state_id'=> 659],
                        [ 'id' => 10062, 'name'=>"Mbengwi", 'state_id'=> 659],
                        [ 'id' => 10063, 'name'=>"Mme", 'state_id'=> 659],
                        [ 'id' => 10064, 'name'=>"Njinikom", 'state_id'=> 659],
                        [ 'id' => 10065, 'name'=>"Nkambe", 'state_id'=> 659],
                        [ 'id' => 10066, 'name'=>"Wum", 'state_id'=> 659],
                        [ 'id' => 10067, 'name'=>"Bafang", 'state_id'=> 660],
                        [ 'id' => 10068, 'name'=>"Bafoussam", 'state_id'=> 660],
                        [ 'id' => 10069, 'name'=>"Bafut", 'state_id'=> 660],
                        [ 'id' => 10070, 'name'=>"Bali", 'state_id'=> 660],
                        [ 'id' => 10071, 'name'=>"Bana", 'state_id'=> 660],
                        [ 'id' => 10072, 'name'=>"Bangangte", 'state_id'=> 660],
                        [ 'id' => 10073, 'name'=>"Djang", 'state_id'=> 660],
                        [ 'id' => 10074, 'name'=>"Fontem", 'state_id'=> 660],
                        [ 'id' => 10075, 'name'=>"Foumban", 'state_id'=> 660],
                        [ 'id' => 10076, 'name'=>"Foumbot", 'state_id'=> 660],
                        [ 'id' => 10077, 'name'=>"Mbouda", 'state_id'=> 660],
                        [ 'id' => 10078, 'name'=>"Akom", 'state_id'=> 661],
                        [ 'id' => 10079, 'name'=>"Ambam", 'state_id'=> 661],
                        [ 'id' => 10080, 'name'=>"Ebolowa", 'state_id'=> 661],
                        [ 'id' => 10081, 'name'=>"Kribi", 'state_id'=> 661],
                        [ 'id' => 10082, 'name'=>"Lolodorf", 'state_id'=> 661],
                        [ 'id' => 10083, 'name'=>"Moloundou", 'state_id'=> 661],
                        [ 'id' => 10084, 'name'=>"Mvangue", 'state_id'=> 661],
                        [ 'id' => 10085, 'name'=>"Sangmelima", 'state_id'=> 661],
                        [ 'id' => 10086, 'name'=>"Buea", 'state_id'=> 662],
                        [ 'id' => 10087, 'name'=>"Idenao", 'state_id'=> 662],
                        [ 'id' => 10088, 'name'=>"Kumba", 'state_id'=> 662],
                        [ 'id' => 10089, 'name'=>"Limbe", 'state_id'=> 662],
                        [ 'id' => 10090, 'name'=>"Mamfe", 'state_id'=> 662],
                        [ 'id' => 10091, 'name'=>"Muyuka", 'state_id'=> 662],
                        [ 'id' => 10092, 'name'=>"Tiko", 'state_id'=> 662],
                        [ 'id' => 10093, 'name'=>"Airdrie", 'state_id'=> 663],
                        [ 'id' => 10094, 'name'=>"Athabasca", 'state_id'=> 663],
                        [ 'id' => 10095, 'name'=>"Banff", 'state_id'=> 663],
                        [ 'id' => 10096, 'name'=>"Barrhead", 'state_id'=> 663],
                        [ 'id' => 10097, 'name'=>"Bassano", 'state_id'=> 663],
                        [ 'id' => 10098, 'name'=>"Beaumont", 'state_id'=> 663],
                        [ 'id' => 10099, 'name'=>"Beaverlodge", 'state_id'=> 663],
                        [ 'id' => 10100, 'name'=>"Black Diamond", 'state_id'=> 663],
                        [ 'id' => 10101, 'name'=>"Blackfalds", 'state_id'=> 663],
                        [ 'id' => 10102, 'name'=>"Blairmore", 'state_id'=> 663],
                        [ 'id' => 10103, 'name'=>"Bon Accord", 'state_id'=> 663],
                        [ 'id' => 10104, 'name'=>"Bonnyville", 'state_id'=> 663],
                        [ 'id' => 10105, 'name'=>"Bow Island", 'state_id'=> 663],
                        [ 'id' => 10106, 'name'=>"Brooks", 'state_id'=> 663],
                        [ 'id' => 10107, 'name'=>"Calgary", 'state_id'=> 663],
                        [ 'id' => 10108, 'name'=>"Calmar", 'state_id'=> 663],
                        [ 'id' => 10109, 'name'=>"Camrose", 'state_id'=> 663],
                        [ 'id' => 10110, 'name'=>"Canmore", 'state_id'=> 663],
                        [ 'id' => 10111, 'name'=>"Cardston", 'state_id'=> 663],
                        [ 'id' => 10112, 'name'=>"Carstairs", 'state_id'=> 663],
                        [ 'id' => 10113, 'name'=>"Chateau Lake Louise", 'state_id'=> 663],
                        [ 'id' => 10114, 'name'=>"Chestermere", 'state_id'=> 663],
                        [ 'id' => 10115, 'name'=>"Clairmont", 'state_id'=> 663],
                        [ 'id' => 10116, 'name'=>"Claresholm", 'state_id'=> 663],
                        [ 'id' => 10117, 'name'=>"Coaldale", 'state_id'=> 663],
                        [ 'id' => 10118, 'name'=>"Coalhurst", 'state_id'=> 663],
                        [ 'id' => 10119, 'name'=>"Cochrane", 'state_id'=> 663],
                        [ 'id' => 10120, 'name'=>"Crossfield", 'state_id'=> 663],
                        [ 'id' => 10121, 'name'=>"Devon", 'state_id'=> 663],
                        [ 'id' => 10122, 'name'=>"Didsbury", 'state_id'=> 663],
                        [ 'id' => 10123, 'name'=>"Drayton Valley", 'state_id'=> 663],
                        [ 'id' => 10124, 'name'=>"Drumheller", 'state_id'=> 663],
                        [ 'id' => 10125, 'name'=>"Edmonton", 'state_id'=> 663],
                        [ 'id' => 10126, 'name'=>"Edson", 'state_id'=> 663],
                        [ 'id' => 10127, 'name'=>"Elk Point", 'state_id'=> 663],
                        [ 'id' => 10128, 'name'=>"Fairview", 'state_id'=> 663],
                        [ 'id' => 10129, 'name'=>"Falher", 'state_id'=> 663],
                        [ 'id' => 10130, 'name'=>"Fort MacLeod", 'state_id'=> 663],
                        [ 'id' => 10131, 'name'=>"Fox Creek", 'state_id'=> 663],
                        [ 'id' => 10132, 'name'=>"Gibbons", 'state_id'=> 663],
                        [ 'id' => 10133, 'name'=>"Grand Centre", 'state_id'=> 663],
                        [ 'id' => 10134, 'name'=>"Grande Cache", 'state_id'=> 663],
                        [ 'id' => 10135, 'name'=>"Grande Prairie", 'state_id'=> 663],
                        [ 'id' => 10136, 'name'=>"Grimshaw", 'state_id'=> 663],
                        [ 'id' => 10137, 'name'=>"Hanna", 'state_id'=> 663],
                        [ 'id' => 10138, 'name'=>"High Level", 'state_id'=> 663],
                        [ 'id' => 10139, 'name'=>"High Prairie", 'state_id'=> 663],
                        [ 'id' => 10140, 'name'=>"High River", 'state_id'=> 663],
                        [ 'id' => 10141, 'name'=>"Hinton", 'state_id'=> 663],
                        [ 'id' => 10142, 'name'=>"Irricana", 'state_id'=> 663],
                        [ 'id' => 10143, 'name'=>"Jasper", 'state_id'=> 663],
                        [ 'id' => 10144, 'name'=>"Killam", 'state_id'=> 663],
                        [ 'id' => 10145, 'name'=>"La Crete", 'state_id'=> 663],
                        [ 'id' => 10146, 'name'=>"Lac la Biche", 'state_id'=> 663],
                        [ 'id' => 10147, 'name'=>"Lacombe", 'state_id'=> 663],
                        [ 'id' => 10148, 'name'=>"Lamont", 'state_id'=> 663],
                        [ 'id' => 10149, 'name'=>"Leduc", 'state_id'=> 663],
                        [ 'id' => 10150, 'name'=>"Lethbridge", 'state_id'=> 663],
                        [ 'id' => 10151, 'name'=>"Lloydminster", 'state_id'=> 663],
                        [ 'id' => 10152, 'name'=>"Magrath", 'state_id'=> 663],
                        [ 'id' => 10153, 'name'=>"Manning", 'state_id'=> 663],
                        [ 'id' => 10154, 'name'=>"Mayerthorpe", 'state_id'=> 663],
                        [ 'id' => 10155, 'name'=>"McMurray", 'state_id'=> 663],
                        [ 'id' => 10156, 'name'=>"Medicine Hat", 'state_id'=> 663],
                        [ 'id' => 10157, 'name'=>"Millet", 'state_id'=> 663],
                        [ 'id' => 10158, 'name'=>"Morinville", 'state_id'=> 663],
                        [ 'id' => 10159, 'name'=>"Nanton", 'state_id'=> 663],
                        [ 'id' => 10160, 'name'=>"Okotoks", 'state_id'=> 663],
                        [ 'id' => 10161, 'name'=>"Olds", 'state_id'=> 663],
                        [ 'id' => 10162, 'name'=>"Peace River", 'state_id'=> 663],
                        [ 'id' => 10163, 'name'=>"Penhold", 'state_id'=> 663],
                        [ 'id' => 10164, 'name'=>"Picture Butte", 'state_id'=> 663],
                        [ 'id' => 10165, 'name'=>"Pincher Creek", 'state_id'=> 663],
                        [ 'id' => 10166, 'name'=>"Ponoka", 'state_id'=> 663],
                        [ 'id' => 10167, 'name'=>"Provost", 'state_id'=> 663],
                        [ 'id' => 10168, 'name'=>"Raymond", 'state_id'=> 663],
                        [ 'id' => 10169, 'name'=>"Red Deer", 'state_id'=> 663],
                        [ 'id' => 10170, 'name'=>"Redwater", 'state_id'=> 663],
                        [ 'id' => 10171, 'name'=>"Rimbey", 'state_id'=> 663],
                        [ 'id' => 10172, 'name'=>"Rocky Mountain House", 'state_id'=> 663],
                        [ 'id' => 10173, 'name'=>"Rocky View", 'state_id'=> 663],
                        [ 'id' => 10174, 'name'=>"Saint Paul", 'state_id'=> 663],
                        [ 'id' => 10175, 'name'=>"Sexsmith", 'state_id'=> 663],
                        [ 'id' => 10176, 'name'=>"Sherwood Park", 'state_id'=> 663],
                        [ 'id' => 10177, 'name'=>"Slave Lake", 'state_id'=> 663],
                        [ 'id' => 10178, 'name'=>"Smoky Lake", 'state_id'=> 663],
                        [ 'id' => 10179, 'name'=>"Spirit River", 'state_id'=> 663],
                        [ 'id' => 10180, 'name'=>"Spruce Grove", 'state_id'=> 663],
                        [ 'id' => 10181, 'name'=>"Stettler", 'state_id'=> 663],
                        [ 'id' => 10182, 'name'=>"Stony Plain", 'state_id'=> 663],
                        [ 'id' => 10183, 'name'=>"Strathmore", 'state_id'=> 663],
                        [ 'id' => 10184, 'name'=>"Sundre", 'state_id'=> 663],
                        [ 'id' => 10185, 'name'=>"Swan Hills", 'state_id'=> 663],
                        [ 'id' => 10186, 'name'=>"Sylvan Lake", 'state_id'=> 663],
                        [ 'id' => 10187, 'name'=>"Taber", 'state_id'=> 663],
                        [ 'id' => 10188, 'name'=>"Three Hills", 'state_id'=> 663],
                        [ 'id' => 10189, 'name'=>"Tofield", 'state_id'=> 663],
                        [ 'id' => 10190, 'name'=>"Two Hills", 'state_id'=> 663],
                        [ 'id' => 10191, 'name'=>"Valleyview", 'state_id'=> 663],
                        [ 'id' => 10192, 'name'=>"Vegreville", 'state_id'=> 663],
                        [ 'id' => 10193, 'name'=>"Vermilion", 'state_id'=> 663],
                        [ 'id' => 10194, 'name'=>"Viking", 'state_id'=> 663],
                        [ 'id' => 10195, 'name'=>"Vulcan", 'state_id'=> 663],
                        [ 'id' => 10196, 'name'=>"Wainwright", 'state_id'=> 663],
                        [ 'id' => 10197, 'name'=>"Wembley", 'state_id'=> 663],
                        [ 'id' => 10198, 'name'=>"Westlock", 'state_id'=> 663],
                        [ 'id' => 10199, 'name'=>"Wetaskiwin", 'state_id'=> 663],
                        [ 'id' => 10200, 'name'=>"Whitecourt", 'state_id'=> 663],
                        [ 'id' => 10201, 'name'=>"Wood Buffalo", 'state_id'=> 663],
                        [ 'id' => 10202, 'name'=>"Altona", 'state_id'=> 665],
                        [ 'id' => 10203, 'name'=>"Beausejour", 'state_id'=> 665],
                        [ 'id' => 10204, 'name'=>"Boissevain", 'state_id'=> 665],
                        [ 'id' => 10205, 'name'=>"Brandon", 'state_id'=> 665],
                        [ 'id' => 10206, 'name'=>"Carberry", 'state_id'=> 665],
                        [ 'id' => 10207, 'name'=>"Carman", 'state_id'=> 665],
                        [ 'id' => 10208, 'name'=>"Dauphin", 'state_id'=> 665],
                        [ 'id' => 10209, 'name'=>"Deloraine", 'state_id'=> 665],
                        [ 'id' => 10210, 'name'=>"Dugald", 'state_id'=> 665],
                        [ 'id' => 10211, 'name'=>"Flin Flon", 'state_id'=> 665],
                        [ 'id' => 10212, 'name'=>"Gimli", 'state_id'=> 665],
                        [ 'id' => 10213, 'name'=>"Hamiota", 'state_id'=> 665],
                        [ 'id' => 10214, 'name'=>"Killarney", 'state_id'=> 665],
                        [ 'id' => 10215, 'name'=>"Lac du Bonnet", 'state_id'=> 665],
                        [ 'id' => 10216, 'name'=>"Leaf Rapids", 'state_id'=> 665],
                        [ 'id' => 10217, 'name'=>"Lorette", 'state_id'=> 665],
                        [ 'id' => 10218, 'name'=>"Melita", 'state_id'=> 665],
                        [ 'id' => 10219, 'name'=>"Minnedosa", 'state_id'=> 665],
                        [ 'id' => 10220, 'name'=>"Morden", 'state_id'=> 665],
                        [ 'id' => 10221, 'name'=>"Morris", 'state_id'=> 665],
                        [ 'id' => 10222, 'name'=>"Neepawa", 'state_id'=> 665],
                        [ 'id' => 10223, 'name'=>"Niverville", 'state_id'=> 665],
                        [ 'id' => 10224, 'name'=>"Pinawa", 'state_id'=> 665],
                        [ 'id' => 10225, 'name'=>"Portage la Prairie", 'state_id'=> 665],
                        [ 'id' => 10226, 'name'=>"Ritchot", 'state_id'=> 665],
                        [ 'id' => 10227, 'name'=>"Rivers", 'state_id'=> 665],
                        [ 'id' => 10228, 'name'=>"Roblin", 'state_id'=> 665],
                        [ 'id' => 10229, 'name'=>"Saint Adolphe", 'state_id'=> 665],
                        [ 'id' => 10230, 'name'=>"Sainte Anne", 'state_id'=> 665],
                        [ 'id' => 10231, 'name'=>"Sainte Rose du Lac", 'state_id'=> 665],
                        [ 'id' => 10232, 'name'=>"Selkirk", 'state_id'=> 665],
                        [ 'id' => 10233, 'name'=>"Shilo", 'state_id'=> 665],
                        [ 'id' => 10234, 'name'=>"Snow Lake", 'state_id'=> 665],
                        [ 'id' => 10235, 'name'=>"Souris", 'state_id'=> 665],
                        [ 'id' => 10236, 'name'=>"Springfield", 'state_id'=> 665],
                        [ 'id' => 10237, 'name'=>"Steinbach", 'state_id'=> 665],
                        [ 'id' => 10238, 'name'=>"Stonewall", 'state_id'=> 665],
                        [ 'id' => 10239, 'name'=>"Stony Mountain", 'state_id'=> 665],
                        [ 'id' => 10240, 'name'=>"Swan River", 'state_id'=> 665],
                        [ 'id' => 10241, 'name'=>"The Pas", 'state_id'=> 665],
                        [ 'id' => 10242, 'name'=>"Thompson", 'state_id'=> 665],
                        [ 'id' => 10243, 'name'=>"Virden", 'state_id'=> 665],
                        [ 'id' => 10244, 'name'=>"Winkler", 'state_id'=> 665],
                        [ 'id' => 10245, 'name'=>"Winnipeg", 'state_id'=> 665],
                        [ 'id' => 10246, 'name'=>"Clyde River", 'state_id'=> 670],
                        [ 'id' => 10247, 'name'=>"Iqaluit", 'state_id'=> 670],
                        [ 'id' => 10248, 'name'=>"Kangerdlinerk", 'state_id'=> 670],
                        [ 'id' => 10249, 'name'=>"Oqsuqtooq", 'state_id'=> 670],
                        [ 'id' => 10250, 'name'=>"Pangnirtung", 'state_id'=> 670],
                        [ 'id' => 10251, 'name'=>"Tununirusiq", 'state_id'=> 670],
                        [ 'id' => 10252, 'name'=>"Acton", 'state_id'=> 671],
                        [ 'id' => 10253, 'name'=>"Ajax", 'state_id'=> 671],
                        [ 'id' => 10254, 'name'=>"Alexandria", 'state_id'=> 671],
                        [ 'id' => 10255, 'name'=>"Alfred", 'state_id'=> 671],
                        [ 'id' => 10256, 'name'=>"Alliston", 'state_id'=> 671],
                        [ 'id' => 10257, 'name'=>"Almonte", 'state_id'=> 671],
                        [ 'id' => 10258, 'name'=>"Amherstburg", 'state_id'=> 671],
                        [ 'id' => 10259, 'name'=>"Amigo Beach", 'state_id'=> 671],
                        [ 'id' => 10260, 'name'=>"Angus-Borden", 'state_id'=> 671],
                        [ 'id' => 10261, 'name'=>"Arnprior", 'state_id'=> 671],
                        [ 'id' => 10262, 'name'=>"Arthur", 'state_id'=> 671],
                        [ 'id' => 10263, 'name'=>"Athens", 'state_id'=> 671],
                        [ 'id' => 10264, 'name'=>"Atikokan", 'state_id'=> 671],
                        [ 'id' => 10265, 'name'=>"Attawapiskat", 'state_id'=> 671],
                        [ 'id' => 10266, 'name'=>"Aurora", 'state_id'=> 671],
                        [ 'id' => 10267, 'name'=>"Aylmer", 'state_id'=> 671],
                        [ 'id' => 10268, 'name'=>"Ayr", 'state_id'=> 671],
                        [ 'id' => 10269, 'name'=>"Barrie", 'state_id'=> 671],
                        [ 'id' => 10270, 'name'=>"Barry''s Bay", 'state_id'=> 671],
                        [ 'id' => 10271, 'name'=>"Beamsville", 'state_id'=> 671],
                        [ 'id' => 10272, 'name'=>"Beaverton", 'state_id'=> 671],
                        [ 'id' => 10273, 'name'=>"Beeton", 'state_id'=> 671],
                        [ 'id' => 10274, 'name'=>"Belleville", 'state_id'=> 671],
                        [ 'id' => 10275, 'name'=>"Belmont", 'state_id'=> 671],
                        [ 'id' => 10276, 'name'=>"Blenheim", 'state_id'=> 671],
                        [ 'id' => 10277, 'name'=>"Blind River", 'state_id'=> 671],
                        [ 'id' => 10278, 'name'=>"Bobcaygeon", 'state_id'=> 671],
                        [ 'id' => 10279, 'name'=>"Bolton", 'state_id'=> 671],
                        [ 'id' => 10280, 'name'=>"Bourget", 'state_id'=> 671],
                        [ 'id' => 10281, 'name'=>"Bowmanville-Newcastle", 'state_id'=> 671],
                        [ 'id' => 10282, 'name'=>"Bracebridge", 'state_id'=> 671],
                        [ 'id' => 10283, 'name'=>"Bradford", 'state_id'=> 671],
                        [ 'id' => 10284, 'name'=>"Brampton", 'state_id'=> 671],
                        [ 'id' => 10285, 'name'=>"Brantford", 'state_id'=> 671],
                        [ 'id' => 10286, 'name'=>"Bridgenorth-Chemong Park Area", 'state_id'=> 671],
                        [ 'id' => 10287, 'name'=>"Brighton", 'state_id'=> 671],
                        [ 'id' => 10288, 'name'=>"Brockville", 'state_id'=> 671],
                        [ 'id' => 10289, 'name'=>"Brooklin", 'state_id'=> 671],
                        [ 'id' => 10290, 'name'=>"Brussels", 'state_id'=> 671],
                        [ 'id' => 10291, 'name'=>"Burford", 'state_id'=> 671],
                        [ 'id' => 10292, 'name'=>"Burlington", 'state_id'=> 671],
                        [ 'id' => 10293, 'name'=>"Caledon", 'state_id'=> 671],
                        [ 'id' => 10294, 'name'=>"Caledon East", 'state_id'=> 671],
                        [ 'id' => 10295, 'name'=>"Caledonia", 'state_id'=> 671],
                        [ 'id' => 10296, 'name'=>"Cambridge", 'state_id'=> 671],
                        [ 'id' => 10297, 'name'=>"Campbellford", 'state_id'=> 671],
                        [ 'id' => 10298, 'name'=>"Campbellville", 'state_id'=> 671],
                        [ 'id' => 10299, 'name'=>"Cannington", 'state_id'=> 671],
                        [ 'id' => 10300, 'name'=>"Capreol", 'state_id'=> 671],
                        [ 'id' => 10301, 'name'=>"Cardinal", 'state_id'=> 671],
                        [ 'id' => 10302, 'name'=>"Carleton Place", 'state_id'=> 671],
                        [ 'id' => 10303, 'name'=>"Carlisle", 'state_id'=> 671],
                        [ 'id' => 10304, 'name'=>"Casselman", 'state_id'=> 671],
                        [ 'id' => 10305, 'name'=>"Cayuga", 'state_id'=> 671],
                        [ 'id' => 10306, 'name'=>"Chalk River", 'state_id'=> 671],
                        [ 'id' => 10307, 'name'=>"Chapleau", 'state_id'=> 671],
                        [ 'id' => 10308, 'name'=>"Chatham", 'state_id'=> 671],
                        [ 'id' => 10309, 'name'=>"Chesley", 'state_id'=> 671],
                        [ 'id' => 10310, 'name'=>"Chesterville", 'state_id'=> 671],
                        [ 'id' => 10311, 'name'=>"Clinton", 'state_id'=> 671],
                        [ 'id' => 10312, 'name'=>"Cobourg", 'state_id'=> 671],
                        [ 'id' => 10313, 'name'=>"Cochrane", 'state_id'=> 671],
                        [ 'id' => 10314, 'name'=>"Colborne", 'state_id'=> 671],
                        [ 'id' => 10315, 'name'=>"Colchester", 'state_id'=> 671],
                        [ 'id' => 10316, 'name'=>"Collingwood", 'state_id'=> 671],
                        [ 'id' => 10317, 'name'=>"Concord", 'state_id'=> 671],
                        [ 'id' => 10318, 'name'=>"Constance Bay", 'state_id'=> 671],
                        [ 'id' => 10319, 'name'=>"Cookstown", 'state_id'=> 671],
                        [ 'id' => 10320, 'name'=>"Cornwall", 'state_id'=> 671],
                        [ 'id' => 10321, 'name'=>"Creemore", 'state_id'=> 671],
                        [ 'id' => 10322, 'name'=>"Crystal Beach", 'state_id'=> 671],
                        [ 'id' => 10323, 'name'=>"Deep River", 'state_id'=> 671],
                        [ 'id' => 10324, 'name'=>"Delhi", 'state_id'=> 671],
                        [ 'id' => 10325, 'name'=>"Deseronto", 'state_id'=> 671],
                        [ 'id' => 10326, 'name'=>"Downsview", 'state_id'=> 671],
                        [ 'id' => 10327, 'name'=>"Drayton", 'state_id'=> 671],
                        [ 'id' => 10328, 'name'=>"Dresden", 'state_id'=> 671],
                        [ 'id' => 10329, 'name'=>"Dryden", 'state_id'=> 671],
                        [ 'id' => 10330, 'name'=>"Dundalk", 'state_id'=> 671],
                        [ 'id' => 10331, 'name'=>"Dunnville", 'state_id'=> 671],
                        [ 'id' => 10332, 'name'=>"Durham", 'state_id'=> 671],
                        [ 'id' => 10333, 'name'=>"Dutton", 'state_id'=> 671],
                        [ 'id' => 10334, 'name'=>"Eganville", 'state_id'=> 671],
                        [ 'id' => 10335, 'name'=>"Elliot Lake", 'state_id'=> 671],
                        [ 'id' => 10336, 'name'=>"Elmira", 'state_id'=> 671],
                        [ 'id' => 10337, 'name'=>"Elmvale", 'state_id'=> 671],
                        [ 'id' => 10338, 'name'=>"Embrun", 'state_id'=> 671],
                        [ 'id' => 10339, 'name'=>"Englehart", 'state_id'=> 671],
                        [ 'id' => 10340, 'name'=>"Erin", 'state_id'=> 671],
                        [ 'id' => 10341, 'name'=>"Espanola", 'state_id'=> 671],
                        [ 'id' => 10342, 'name'=>"Essex", 'state_id'=> 671],
                        [ 'id' => 10343, 'name'=>"Etobicoke", 'state_id'=> 671],
                        [ 'id' => 10344, 'name'=>"Everett", 'state_id'=> 671],
                        [ 'id' => 10345, 'name'=>"Exeter", 'state_id'=> 671],
                        [ 'id' => 10346, 'name'=>"Fenelon Falls", 'state_id'=> 671],
                        [ 'id' => 10347, 'name'=>"Fergus", 'state_id'=> 671],
                        [ 'id' => 10348, 'name'=>"Forest", 'state_id'=> 671],
                        [ 'id' => 10349, 'name'=>"Fort Erie", 'state_id'=> 671],
                        [ 'id' => 10350, 'name'=>"Fort Frances", 'state_id'=> 671],
                        [ 'id' => 10351, 'name'=>"Frankford", 'state_id'=> 671],
                        [ 'id' => 10352, 'name'=>"Gananoque", 'state_id'=> 671],
                        [ 'id' => 10353, 'name'=>"Georgetown", 'state_id'=> 671],
                        [ 'id' => 10354, 'name'=>"Georgina", 'state_id'=> 671],
                        [ 'id' => 10355, 'name'=>"Geraldton", 'state_id'=> 671],
                        [ 'id' => 10356, 'name'=>"Glencoe", 'state_id'=> 671],
                        [ 'id' => 10357, 'name'=>"Goderich", 'state_id'=> 671],
                        [ 'id' => 10358, 'name'=>"Golden", 'state_id'=> 671],
                        [ 'id' => 10359, 'name'=>"Gormley", 'state_id'=> 671],
                        [ 'id' => 10360, 'name'=>"Grand Bend", 'state_id'=> 671],
                        [ 'id' => 10361, 'name'=>"Grand Valley", 'state_id'=> 671],
                        [ 'id' => 10362, 'name'=>"Gravenhurst", 'state_id'=> 671],
                        [ 'id' => 10363, 'name'=>"Guelph", 'state_id'=> 671],
                        [ 'id' => 10364, 'name'=>"Hagersville", 'state_id'=> 671],
                        [ 'id' => 10365, 'name'=>"Haileybury", 'state_id'=> 671],
                        [ 'id' => 10366, 'name'=>"Hamilton", 'state_id'=> 671],
                        [ 'id' => 10367, 'name'=>"Hanover", 'state_id'=> 671],
                        [ 'id' => 10368, 'name'=>"Harriston", 'state_id'=> 671],
                        [ 'id' => 10369, 'name'=>"Harrow", 'state_id'=> 671],
                        [ 'id' => 10370, 'name'=>"Hastings", 'state_id'=> 671],
                        [ 'id' => 10371, 'name'=>"Havelock", 'state_id'=> 671],
                        [ 'id' => 10372, 'name'=>"Hawkesbury", 'state_id'=> 671],
                        [ 'id' => 10373, 'name'=>"Hearst", 'state_id'=> 671],
                        [ 'id' => 10374, 'name'=>"Hensall", 'state_id'=> 671],
                        [ 'id' => 10375, 'name'=>"Hillsburgh", 'state_id'=> 671],
                        [ 'id' => 10376, 'name'=>"Hornepayne", 'state_id'=> 671],
                        [ 'id' => 10377, 'name'=>"Huntsville", 'state_id'=> 671],
                        [ 'id' => 10378, 'name'=>"Ingersoll", 'state_id'=> 671],
                        [ 'id' => 10379, 'name'=>"Innisfil", 'state_id'=> 671],
                        [ 'id' => 10380, 'name'=>"Iroquois", 'state_id'=> 671],
                        [ 'id' => 10381, 'name'=>"Iroquois Falls", 'state_id'=> 671],
                        [ 'id' => 10382, 'name'=>"Jarvis", 'state_id'=> 671],
                        [ 'id' => 10383, 'name'=>"Kanata", 'state_id'=> 671],
                        [ 'id' => 10384, 'name'=>"Kapuskasing", 'state_id'=> 671],
                        [ 'id' => 10385, 'name'=>"Kars", 'state_id'=> 671],
                        [ 'id' => 10386, 'name'=>"Kemptville", 'state_id'=> 671],
                        [ 'id' => 10387, 'name'=>"Kenora", 'state_id'=> 671],
                        [ 'id' => 10388, 'name'=>"Kincardine", 'state_id'=> 671],
                        [ 'id' => 10389, 'name'=>"Kingston", 'state_id'=> 671],
                        [ 'id' => 10390, 'name'=>"Kirkland Lake", 'state_id'=> 671],
                        [ 'id' => 10391, 'name'=>"Kitchener", 'state_id'=> 671],
                        [ 'id' => 10392, 'name'=>"L''Original", 'state_id'=> 671],
                        [ 'id' => 10393, 'name'=>"Lakefield", 'state_id'=> 671],
                        [ 'id' => 10394, 'name'=>"Lanark", 'state_id'=> 671],
                        [ 'id' => 10395, 'name'=>"Leamington", 'state_id'=> 671],
                        [ 'id' => 10396, 'name'=>"Lindsay", 'state_id'=> 671],
                        [ 'id' => 10397, 'name'=>"Listowel", 'state_id'=> 671],
                        [ 'id' => 10398, 'name'=>"Little Current", 'state_id'=> 671],
                        [ 'id' => 10399, 'name'=>"Lively", 'state_id'=> 671],
                        [ 'id' => 10400, 'name'=>"London", 'state_id'=> 671],
                        [ 'id' => 10401, 'name'=>"Longlac", 'state_id'=> 671],
                        [ 'id' => 10402, 'name'=>"Lucan", 'state_id'=> 671],
                        [ 'id' => 10403, 'name'=>"Lucknow", 'state_id'=> 671],
                        [ 'id' => 10404, 'name'=>"Madoc", 'state_id'=> 671],
                        [ 'id' => 10405, 'name'=>"Manitouwadge", 'state_id'=> 671],
                        [ 'id' => 10406, 'name'=>"Maple", 'state_id'=> 671],
                        [ 'id' => 10407, 'name'=>"Marathon", 'state_id'=> 671],
                        [ 'id' => 10408, 'name'=>"Markdale", 'state_id'=> 671],
                        [ 'id' => 10409, 'name'=>"Markham", 'state_id'=> 671],
                        [ 'id' => 10410, 'name'=>"Marmora", 'state_id'=> 671],
                        [ 'id' => 10411, 'name'=>"Mattawa", 'state_id'=> 671],
                        [ 'id' => 10412, 'name'=>"Meaford", 'state_id'=> 671],
                        [ 'id' => 10413, 'name'=>"Metcalfe", 'state_id'=> 671],
                        [ 'id' => 10414, 'name'=>"Midland", 'state_id'=> 671],
                        [ 'id' => 10415, 'name'=>"Mildmay", 'state_id'=> 671],
                        [ 'id' => 10416, 'name'=>"Millbrook", 'state_id'=> 671],
                        [ 'id' => 10417, 'name'=>"Milton", 'state_id'=> 671],
                        [ 'id' => 10418, 'name'=>"Milverton", 'state_id'=> 671],
                        [ 'id' => 10419, 'name'=>"Mississauga", 'state_id'=> 671],
                        [ 'id' => 10420, 'name'=>"Mississauga Beach", 'state_id'=> 671],
                        [ 'id' => 10421, 'name'=>"Mitchell", 'state_id'=> 671],
                        [ 'id' => 10422, 'name'=>"Moose Factory", 'state_id'=> 671],
                        [ 'id' => 10423, 'name'=>"Morrisburg", 'state_id'=> 671],
                        [ 'id' => 10424, 'name'=>"Mount Albert", 'state_id'=> 671],
                        [ 'id' => 10425, 'name'=>"Mount Brydges", 'state_id'=> 671],
                        [ 'id' => 10426, 'name'=>"Mount Forest", 'state_id'=> 671],
                        [ 'id' => 10427, 'name'=>"Munster", 'state_id'=> 671],
                        [ 'id' => 10428, 'name'=>"Nanticoke", 'state_id'=> 671],
                        [ 'id' => 10429, 'name'=>"Napanee", 'state_id'=> 671],
                        [ 'id' => 10430, 'name'=>"Nepean", 'state_id'=> 671],
                        [ 'id' => 10431, 'name'=>"New Hamburg", 'state_id'=> 671],
                        [ 'id' => 10432, 'name'=>"Newmarket", 'state_id'=> 671],
                        [ 'id' => 10433, 'name'=>"Newtonville", 'state_id'=> 671],
                        [ 'id' => 10434, 'name'=>"Nobleton", 'state_id'=> 671],
                        [ 'id' => 10435, 'name'=>"North Bay", 'state_id'=> 671],
                        [ 'id' => 10436, 'name'=>"North Gower", 'state_id'=> 671],
                        [ 'id' => 10437, 'name'=>"North York", 'state_id'=> 671],
                        [ 'id' => 10438, 'name'=>"Norwich", 'state_id'=> 671],
                        [ 'id' => 10439, 'name'=>"Norwood", 'state_id'=> 671],
                        [ 'id' => 10440, 'name'=>"Oakville", 'state_id'=> 671],
                        [ 'id' => 10441, 'name'=>"Omemee", 'state_id'=> 671],
                        [ 'id' => 10442, 'name'=>"Onaping-Levack", 'state_id'=> 671],
                        [ 'id' => 10443, 'name'=>"Ontario", 'state_id'=> 671],
                        [ 'id' => 10444, 'name'=>"Orangeville", 'state_id'=> 671],
                        [ 'id' => 10445, 'name'=>"Orillia", 'state_id'=> 671],
                        [ 'id' => 10446, 'name'=>"Orono", 'state_id'=> 671],
                        [ 'id' => 10447, 'name'=>"Osgoode", 'state_id'=> 671],
                        [ 'id' => 10448, 'name'=>"Oshawa", 'state_id'=> 671],
                        [ 'id' => 10449, 'name'=>"Ottawa", 'state_id'=> 671],
                        [ 'id' => 10450, 'name'=>"Owen Sound", 'state_id'=> 671],
                        [ 'id' => 10451, 'name'=>"Paisley", 'state_id'=> 671],
                        [ 'id' => 10452, 'name'=>"Palmerston", 'state_id'=> 671],
                        [ 'id' => 10453, 'name'=>"Paris", 'state_id'=> 671],
                        [ 'id' => 10454, 'name'=>"Parkhill", 'state_id'=> 671],
                        [ 'id' => 10455, 'name'=>"Parry Sound", 'state_id'=> 671],
                        [ 'id' => 10456, 'name'=>"Pembroke", 'state_id'=> 671],
                        [ 'id' => 10457, 'name'=>"Perth", 'state_id'=> 671],
                        [ 'id' => 10458, 'name'=>"Petawawa", 'state_id'=> 671],
                        [ 'id' => 10459, 'name'=>"Peterborough", 'state_id'=> 671],
                        [ 'id' => 10460, 'name'=>"Petrolia", 'state_id'=> 671],
                        [ 'id' => 10461, 'name'=>"Pickering", 'state_id'=> 671],
                        [ 'id' => 10462, 'name'=>"Picton", 'state_id'=> 671],
                        [ 'id' => 10463, 'name'=>"Porcupine", 'state_id'=> 671],
                        [ 'id' => 10464, 'name'=>"Port Credit", 'state_id'=> 671],
                        [ 'id' => 10465, 'name'=>"Port Dover", 'state_id'=> 671],
                        [ 'id' => 10466, 'name'=>"Port Elgin", 'state_id'=> 671],
                        [ 'id' => 10467, 'name'=>"Port Hope", 'state_id'=> 671],
                        [ 'id' => 10468, 'name'=>"Port Perry", 'state_id'=> 671],
                        [ 'id' => 10469, 'name'=>"Port Stanley", 'state_id'=> 671],
                        [ 'id' => 10470, 'name'=>"Powassan", 'state_id'=> 671],
                        [ 'id' => 10471, 'name'=>"Prescott", 'state_id'=> 671],
                        [ 'id' => 10472, 'name'=>"Queensville", 'state_id'=> 671],
                        [ 'id' => 10473, 'name'=>"Renfrew", 'state_id'=> 671],
                        [ 'id' => 10474, 'name'=>"Richmond", 'state_id'=> 671],
                        [ 'id' => 10475, 'name'=>"Richmond Hill", 'state_id'=> 671],
                        [ 'id' => 10476, 'name'=>"Ridgetown", 'state_id'=> 671],
                        [ 'id' => 10477, 'name'=>"Rockland", 'state_id'=> 671],
                        [ 'id' => 10478, 'name'=>"Rockwood", 'state_id'=> 671],
                        [ 'id' => 10479, 'name'=>"Rodney", 'state_id'=> 671],
                        [ 'id' => 10480, 'name'=>"Saint Catharines", 'state_id'=> 671],
                        [ 'id' => 10481, 'name'=>"Saint Catharines-Niagara", 'state_id'=> 671],
                        [ 'id' => 10482, 'name'=>"Saint George", 'state_id'=> 671],
                        [ 'id' => 10483, 'name'=>"Saint Jacobs", 'state_id'=> 671],
                        [ 'id' => 10484, 'name'=>"Saint Marys", 'state_id'=> 671],
                        [ 'id' => 10485, 'name'=>"Saint Thomas", 'state_id'=> 671],
                        [ 'id' => 10486, 'name'=>"Sarnia", 'state_id'=> 671],
                        [ 'id' => 10487, 'name'=>"Sault Sainte Marie", 'state_id'=> 671],
                        [ 'id' => 10488, 'name'=>"Scarborough", 'state_id'=> 671],
                        [ 'id' => 10489, 'name'=>"Schomberg", 'state_id'=> 671],
                        [ 'id' => 10490, 'name'=>"Seaforth", 'state_id'=> 671],
                        [ 'id' => 10491, 'name'=>"Shelburne", 'state_id'=> 671],
                        [ 'id' => 10492, 'name'=>"Simcoe", 'state_id'=> 671],
                        [ 'id' => 10493, 'name'=>"Sioux Lookout", 'state_id'=> 671],
                        [ 'id' => 10494, 'name'=>"Smiths Falls", 'state_id'=> 671],
                        [ 'id' => 10495, 'name'=>"Smithville", 'state_id'=> 671],
                        [ 'id' => 10496, 'name'=>"South River", 'state_id'=> 671],
                        [ 'id' => 10497, 'name'=>"Southampton", 'state_id'=> 671],
                        [ 'id' => 10498, 'name'=>"Stayner", 'state_id'=> 671],
                        [ 'id' => 10499, 'name'=>"Stirling", 'state_id'=> 671],
                        [ 'id' => 10500, 'name'=>"Stoney Creek", 'state_id'=> 671],
                        [ 'id' => 10501, 'name'=>"Stoney Point", 'state_id'=> 671],
                        [ 'id' => 10502, 'name'=>"Stouffville", 'state_id'=> 671],
                        [ 'id' => 10503, 'name'=>"Stratford", 'state_id'=> 671],
                        [ 'id' => 10504, 'name'=>"Strathroy", 'state_id'=> 671],
                        [ 'id' => 10505, 'name'=>"Sturgeon Falls", 'state_id'=> 671],
                        [ 'id' => 10506, 'name'=>"Sudbury", 'state_id'=> 671],
                        [ 'id' => 10507, 'name'=>"Sutton", 'state_id'=> 671],
                        [ 'id' => 10508, 'name'=>"Tavistock", 'state_id'=> 671],
                        [ 'id' => 10509, 'name'=>"Teeswater", 'state_id'=> 671],
                        [ 'id' => 10510, 'name'=>"Terrace Bay", 'state_id'=> 671],
                        [ 'id' => 10511, 'name'=>"Thamesford", 'state_id'=> 671],
                        [ 'id' => 10512, 'name'=>"Thessalon", 'state_id'=> 671],
                        [ 'id' => 10513, 'name'=>"Thornbury", 'state_id'=> 671],
                        [ 'id' => 10514, 'name'=>"Thornhill", 'state_id'=> 671],
                        [ 'id' => 10515, 'name'=>"Thunder Bay", 'state_id'=> 671],
                        [ 'id' => 10516, 'name'=>"Tilbury", 'state_id'=> 671],
                        [ 'id' => 10517, 'name'=>"Tilsonburg", 'state_id'=> 671],
                        [ 'id' => 10518, 'name'=>"Timmins", 'state_id'=> 671],
                        [ 'id' => 10519, 'name'=>"Toronto", 'state_id'=> 671],
                        [ 'id' => 10520, 'name'=>"Tory Hill", 'state_id'=> 671],
                        [ 'id' => 10521, 'name'=>"Tottenham", 'state_id'=> 671],
                        [ 'id' => 10522, 'name'=>"Tweed", 'state_id'=> 671],
                        [ 'id' => 10523, 'name'=>"Uxbridge", 'state_id'=> 671],
                        [ 'id' => 10524, 'name'=>"Valley East", 'state_id'=> 671],
                        [ 'id' => 10525, 'name'=>"Vankleek Hill", 'state_id'=> 671],
                        [ 'id' => 10526, 'name'=>"Vaughan", 'state_id'=> 671],
                        [ 'id' => 10527, 'name'=>"Vineland", 'state_id'=> 671],
                        [ 'id' => 10528, 'name'=>"Walkerton", 'state_id'=> 671],
                        [ 'id' => 10529, 'name'=>"Wallaceburg", 'state_id'=> 671],
                        [ 'id' => 10530, 'name'=>"Wasaga Beach", 'state_id'=> 671],
                        [ 'id' => 10531, 'name'=>"Waterdown", 'state_id'=> 671],
                        [ 'id' => 10532, 'name'=>"Waterford", 'state_id'=> 671],
                        [ 'id' => 10533, 'name'=>"Waterloo", 'state_id'=> 671],
                        [ 'id' => 10534, 'name'=>"Watford", 'state_id'=> 671],
                        [ 'id' => 10535, 'name'=>"Wawa", 'state_id'=> 671],
                        [ 'id' => 10536, 'name'=>"Welland", 'state_id'=> 671],
                        [ 'id' => 10537, 'name'=>"Wellesley", 'state_id'=> 671],
                        [ 'id' => 10538, 'name'=>"Wellington", 'state_id'=> 671],
                        [ 'id' => 10539, 'name'=>"West Lorne", 'state_id'=> 671],
                        [ 'id' => 10540, 'name'=>"Wheatley", 'state_id'=> 671],
                        [ 'id' => 10541, 'name'=>"Whitby", 'state_id'=> 671],
                        [ 'id' => 10542, 'name'=>"Whitchurch-Stouffville", 'state_id'=> 671],
                        [ 'id' => 10543, 'name'=>"Wiarton", 'state_id'=> 671],
                        [ 'id' => 10544, 'name'=>"Wikwemikong", 'state_id'=> 671],
                        [ 'id' => 10545, 'name'=>"Willowdale", 'state_id'=> 671],
                        [ 'id' => 10546, 'name'=>"Winchester", 'state_id'=> 671],
                        [ 'id' => 10547, 'name'=>"Windsor", 'state_id'=> 671],
                        [ 'id' => 10548, 'name'=>"Wingham", 'state_id'=> 671],
                        [ 'id' => 10549, 'name'=>"Woodbridge", 'state_id'=> 671],
                        [ 'id' => 10550, 'name'=>"Woodstock", 'state_id'=> 671],
                        [ 'id' => 10551, 'name'=>"Wyoming", 'state_id'=> 671],
                        [ 'id' => 10552, 'name'=>"Acton Vale", 'state_id'=> 673],
                        [ 'id' => 10553, 'name'=>"Albanel", 'state_id'=> 673],
                        [ 'id' => 10554, 'name'=>"Alencon", 'state_id'=> 673],
                        [ 'id' => 10555, 'name'=>"Alma", 'state_id'=> 673],
                        [ 'id' => 10556, 'name'=>"Amos", 'state_id'=> 673],
                        [ 'id' => 10557, 'name'=>"Amqui", 'state_id'=> 673],
                        [ 'id' => 10558, 'name'=>"Anjou", 'state_id'=> 673],
                        [ 'id' => 10559, 'name'=>"Asbestos", 'state_id'=> 673],
                        [ 'id' => 10560, 'name'=>"Bagotville", 'state_id'=> 673],
                        [ 'id' => 10561, 'name'=>"Baie-Comeau", 'state_id'=> 673],
                        [ 'id' => 10562, 'name'=>"Baie-Saint-Paul", 'state_id'=> 673],
                        [ 'id' => 10563, 'name'=>"Barraute", 'state_id'=> 673],
                        [ 'id' => 10564, 'name'=>"Beauceville", 'state_id'=> 673],
                        [ 'id' => 10565, 'name'=>"Beaupre", 'state_id'=> 673],
                        [ 'id' => 10566, 'name'=>"Bedford", 'state_id'=> 673],
                        [ 'id' => 10567, 'name'=>"Beloeil", 'state_id'=> 673],
                        [ 'id' => 10568, 'name'=>"Bernierville", 'state_id'=> 673],
                        [ 'id' => 10569, 'name'=>"Berthierville", 'state_id'=> 673],
                        [ 'id' => 10570, 'name'=>"Betsiamites", 'state_id'=> 673],
                        [ 'id' => 10571, 'name'=>"Boisbriand", 'state_id'=> 673],
                        [ 'id' => 10572, 'name'=>"Bonaventure", 'state_id'=> 673],
                        [ 'id' => 10573, 'name'=>"Boucherville", 'state_id'=> 673],
                        [ 'id' => 10574, 'name'=>"Bromont", 'state_id'=> 673],
                        [ 'id' => 10575, 'name'=>"Brossard", 'state_id'=> 673],
                        [ 'id' => 10576, 'name'=>"Brownsburg", 'state_id'=> 673],
                        [ 'id' => 10577, 'name'=>"Buckingham", 'state_id'=> 673],
                        [ 'id' => 10578, 'name'=>"Cabano", 'state_id'=> 673],
                        [ 'id' => 10579, 'name'=>"Candiac", 'state_id'=> 673],
                        [ 'id' => 10580, 'name'=>"Cap-Chat", 'state_id'=> 673],
                        [ 'id' => 10581, 'name'=>"Cap-aux-Meules", 'state_id'=> 673],
                        [ 'id' => 10582, 'name'=>"Carleton", 'state_id'=> 673],
                        [ 'id' => 10583, 'name'=>"Causapscal", 'state_id'=> 673],
                        [ 'id' => 10584, 'name'=>"Chandler", 'state_id'=> 673],
                        [ 'id' => 10585, 'name'=>"Chapais", 'state_id'=> 673],
                        [ 'id' => 10586, 'name'=>"Charlesbourg", 'state_id'=> 673],
                        [ 'id' => 10587, 'name'=>"Chateau-Richer", 'state_id'=> 673],
                        [ 'id' => 10588, 'name'=>"Chibougamou", 'state_id'=> 673],
                        [ 'id' => 10589, 'name'=>"Chicoutimi-Jonquiere", 'state_id'=> 673],
                        [ 'id' => 10590, 'name'=>"Chisasibi", 'state_id'=> 673],
                        [ 'id' => 10591, 'name'=>"Chute-aux-Outardes", 'state_id'=> 673],
                        [ 'id' => 10592, 'name'=>"Clermont", 'state_id'=> 673],
                        [ 'id' => 10593, 'name'=>"Coaticook", 'state_id'=> 673],
                        [ 'id' => 10594, 'name'=>"Coleraine", 'state_id'=> 673],
                        [ 'id' => 10595, 'name'=>"Contrecoeur", 'state_id'=> 673],
                        [ 'id' => 10596, 'name'=>"Cookshire", 'state_id'=> 673],
                        [ 'id' => 10597, 'name'=>"Cowansville", 'state_id'=> 673],
                        [ 'id' => 10598, 'name'=>"Crabtree", 'state_id'=> 673],
                        [ 'id' => 10599, 'name'=>"Danville", 'state_id'=> 673],
                        [ 'id' => 10600, 'name'=>"Daveluyville", 'state_id'=> 673],
                        [ 'id' => 10601, 'name'=>"Degelis", 'state_id'=> 673],
                        [ 'id' => 10602, 'name'=>"Desbiens", 'state_id'=> 673],
                        [ 'id' => 10603, 'name'=>"Disraeli", 'state_id'=> 673],
                        [ 'id' => 10604, 'name'=>"Dolbeau", 'state_id'=> 673],
                        [ 'id' => 10605, 'name'=>"Donnacona", 'state_id'=> 673],
                        [ 'id' => 10606, 'name'=>"Dorval", 'state_id'=> 673],
                        [ 'id' => 10607, 'name'=>"Drummondville", 'state_id'=> 673],
                        [ 'id' => 10608, 'name'=>"East Angus", 'state_id'=> 673],
                        [ 'id' => 10609, 'name'=>"East Broughton", 'state_id'=> 673],
                        [ 'id' => 10610, 'name'=>"Farnham", 'state_id'=> 673],
                        [ 'id' => 10611, 'name'=>"Ferme-Neuve", 'state_id'=> 673],
                        [ 'id' => 10612, 'name'=>"Fermont", 'state_id'=> 673],
                        [ 'id' => 10613, 'name'=>"Filion", 'state_id'=> 673],
                        [ 'id' => 10614, 'name'=>"Forestville", 'state_id'=> 673],
                        [ 'id' => 10615, 'name'=>"Fort-Coulonge", 'state_id'=> 673],
                        [ 'id' => 10616, 'name'=>"Gaspe", 'state_id'=> 673],
                        [ 'id' => 10617, 'name'=>"Gentilly", 'state_id'=> 673],
                        [ 'id' => 10618, 'name'=>"Granby", 'state_id'=> 673],
                        [ 'id' => 10619, 'name'=>"Grande-Riviere", 'state_id'=> 673],
                        [ 'id' => 10620, 'name'=>"Grenville", 'state_id'=> 673],
                        [ 'id' => 10621, 'name'=>"Ham Nord", 'state_id'=> 673],
                        [ 'id' => 10622, 'name'=>"Hampstead", 'state_id'=> 673],
                        [ 'id' => 10623, 'name'=>"Hauterive", 'state_id'=> 673],
                        [ 'id' => 10624, 'name'=>"Havre-Saint-Pierre", 'state_id'=> 673],
                        [ 'id' => 10625, 'name'=>"Hebertville", 'state_id'=> 673],
                        [ 'id' => 10626, 'name'=>"Huntingdon", 'state_id'=> 673],
                        [ 'id' => 10627, 'name'=>"Joliette", 'state_id'=> 673],
                        [ 'id' => 10628, 'name'=>"Kingsey Falls", 'state_id'=> 673],
                        [ 'id' => 10629, 'name'=>"L''Annonciation", 'state_id'=> 673],
                        [ 'id' => 10630, 'name'=>"L''Ascension-de-Notre-Seigneur", 'state_id'=> 673],
                        [ 'id' => 10631, 'name'=>"L''Epiphanie", 'state_id'=> 673],
                        [ 'id' => 10632, 'name'=>"La Malbaie", 'state_id'=> 673],
                        [ 'id' => 10633, 'name'=>"La Pocatiere", 'state_id'=> 673],
                        [ 'id' => 10634, 'name'=>"La Sarre", 'state_id'=> 673],
                        [ 'id' => 10635, 'name'=>"La Tuque", 'state_id'=> 673],
                        [ 'id' => 10636, 'name'=>"Labelle", 'state_id'=> 673],
                        [ 'id' => 10637, 'name'=>"Lac-Etchemin", 'state_id'=> 673],
                        [ 'id' => 10638, 'name'=>"Lac-Lapierre", 'state_id'=> 673],
                        [ 'id' => 10639, 'name'=>"Lac-Megantic", 'state_id'=> 673],
                        [ 'id' => 10640, 'name'=>"Lac-au-Saumon", 'state_id'=> 673],
                        [ 'id' => 10641, 'name'=>"Lachine", 'state_id'=> 673],
                        [ 'id' => 10642, 'name'=>"Lachute", 'state_id'=> 673],
                        [ 'id' => 10643, 'name'=>"Lacolle", 'state_id'=> 673],
                        [ 'id' => 10644, 'name'=>"Lasalle", 'state_id'=> 673],
                        [ 'id' => 10645, 'name'=>"Laurentides", 'state_id'=> 673],
                        [ 'id' => 10646, 'name'=>"Laurier-Station", 'state_id'=> 673],
                        [ 'id' => 10647, 'name'=>"Laval", 'state_id'=> 673],
                        [ 'id' => 10648, 'name'=>"Lavaltrie", 'state_id'=> 673],
                        [ 'id' => 10649, 'name'=>"Le Bic", 'state_id'=> 673],
                        [ 'id' => 10650, 'name'=>"Lebel-sur-Quevillon", 'state_id'=> 673],
                        [ 'id' => 10651, 'name'=>"Les Cedres", 'state_id'=> 673],
                        [ 'id' => 10652, 'name'=>"Les Coteaux", 'state_id'=> 673],
                        [ 'id' => 10653, 'name'=>"Les Escoumins", 'state_id'=> 673],
                        [ 'id' => 10654, 'name'=>"Liniere", 'state_id'=> 673],
                        [ 'id' => 10655, 'name'=>"Longueuil", 'state_id'=> 673],
                        [ 'id' => 10656, 'name'=>"Louiseville", 'state_id'=> 673],
                        [ 'id' => 10657, 'name'=>"Luceville", 'state_id'=> 673],
                        [ 'id' => 10658, 'name'=>"Macamic", 'state_id'=> 673],
                        [ 'id' => 10659, 'name'=>"Magog", 'state_id'=> 673],
                        [ 'id' => 10660, 'name'=>"Malartic", 'state_id'=> 673],
                        [ 'id' => 10661, 'name'=>"Maniwaki", 'state_id'=> 673],
                        [ 'id' => 10662, 'name'=>"Marieville", 'state_id'=> 673],
                        [ 'id' => 10663, 'name'=>"Maskinonge", 'state_id'=> 673],
                        [ 'id' => 10664, 'name'=>"Matagami", 'state_id'=> 673],
                        [ 'id' => 10665, 'name'=>"Matane", 'state_id'=> 673],
                        [ 'id' => 10666, 'name'=>"Metabetchouan", 'state_id'=> 673],
                        [ 'id' => 10667, 'name'=>"Mirabel", 'state_id'=> 673],
                        [ 'id' => 10668, 'name'=>"Mistissini", 'state_id'=> 673],
                        [ 'id' => 10669, 'name'=>"Mont-Joli", 'state_id'=> 673],
                        [ 'id' => 10670, 'name'=>"Mont-Laurier", 'state_id'=> 673],
                        [ 'id' => 10671, 'name'=>"Montmagny", 'state_id'=> 673],
                        [ 'id' => 10672, 'name'=>"Montreal", 'state_id'=> 673],
                        [ 'id' => 10673, 'name'=>"Murdochville", 'state_id'=> 673],
                        [ 'id' => 10674, 'name'=>"Napierville", 'state_id'=> 673],
                        [ 'id' => 10675, 'name'=>"New Richmond", 'state_id'=> 673],
                        [ 'id' => 10676, 'name'=>"Nicolet", 'state_id'=> 673],
                        [ 'id' => 10677, 'name'=>"Normandin", 'state_id'=> 673],
                        [ 'id' => 10678, 'name'=>"Notre-Dame-du-Bon-Conseil", 'state_id'=> 673],
                        [ 'id' => 10679, 'name'=>"Notre-Dame-du-Lac", 'state_id'=> 673],
                        [ 'id' => 10680, 'name'=>"Notre-Dame-du-Mont-Carmel", 'state_id'=> 673],
                        [ 'id' => 10681, 'name'=>"Oka-Kanesatake", 'state_id'=> 673],
                        [ 'id' => 10682, 'name'=>"Ormstown", 'state_id'=> 673],
                        [ 'id' => 10683, 'name'=>"Papineauville", 'state_id'=> 673],
                        [ 'id' => 10684, 'name'=>"Pierreville", 'state_id'=> 673],
                        [ 'id' => 10685, 'name'=>"Plessisville", 'state_id'=> 673],
                        [ 'id' => 10686, 'name'=>"Pointe-Claire", 'state_id'=> 673],
                        [ 'id' => 10687, 'name'=>"Pont-Rouge", 'state_id'=> 673],
                        [ 'id' => 10688, 'name'=>"Port-Alfred-Bagotville", 'state_id'=> 673],
                        [ 'id' => 10689, 'name'=>"Port-Cartier", 'state_id'=> 673],
                        [ 'id' => 10690, 'name'=>"Portneuf", 'state_id'=> 673],
                        [ 'id' => 10691, 'name'=>"Price", 'state_id'=> 673],
                        [ 'id' => 10692, 'name'=>"Princeville", 'state_id'=> 673],
                        [ 'id' => 10693, 'name'=>"Quebec", 'state_id'=> 673],
                        [ 'id' => 10694, 'name'=>"Rawdon", 'state_id'=> 673],
                        [ 'id' => 10695, 'name'=>"Repentigny", 'state_id'=> 673],
                        [ 'id' => 10696, 'name'=>"Richmond", 'state_id'=> 673],
                        [ 'id' => 10697, 'name'=>"Rigaud", 'state_id'=> 673],
                        [ 'id' => 10698, 'name'=>"Rimouski", 'state_id'=> 673],
                        [ 'id' => 10699, 'name'=>"Riviere-au-Renard", 'state_id'=> 673],
                        [ 'id' => 10700, 'name'=>"Riviere-du-Loup", 'state_id'=> 673],
                        [ 'id' => 10701, 'name'=>"Roberval", 'state_id'=> 673],
                        [ 'id' => 10702, 'name'=>"Rougemont", 'state_id'=> 673],
                        [ 'id' => 10703, 'name'=>"Rouyn-Noranda", 'state_id'=> 673],
                        [ 'id' => 10704, 'name'=>"Saint-Agapit", 'state_id'=> 673],
                        [ 'id' => 10705, 'name'=>"Saint-Alexandre", 'state_id'=> 673],
                        [ 'id' => 10706, 'name'=>"Saint-Alexis-des-Monts", 'state_id'=> 673],
                        [ 'id' => 10707, 'name'=>"Saint-Ambroise", 'state_id'=> 673],
                        [ 'id' => 10708, 'name'=>"Saint-Andre-Avellin", 'state_id'=> 673],
                        [ 'id' => 10709, 'name'=>"Saint-Anselme", 'state_id'=> 673],
                        [ 'id' => 10710, 'name'=>"Saint-Apollinaire", 'state_id'=> 673],
                        [ 'id' => 10711, 'name'=>"Saint-Augustin", 'state_id'=> 673],
                        [ 'id' => 10712, 'name'=>"Saint-Basile-Sud", 'state_id'=> 673],
                        [ 'id' => 10713, 'name'=>"Saint-Bruno", 'state_id'=> 673],
                        [ 'id' => 10714, 'name'=>"Saint-Canut", 'state_id'=> 673],
                        [ 'id' => 10715, 'name'=>"Saint-Cesaire", 'state_id'=> 673],
                        [ 'id' => 10716, 'name'=>"Saint-Cyrill-de-Wendover", 'state_id'=> 673],
                        [ 'id' => 10717, 'name'=>"Saint-Damase", 'state_id'=> 673],
                        [ 'id' => 10718, 'name'=>"Saint-Damien-de-Buckland", 'state_id'=> 673],
                        [ 'id' => 10719, 'name'=>"Saint-Denis", 'state_id'=> 673],
                        [ 'id' => 10720, 'name'=>"Saint-Donat-de-Montcalm", 'state_id'=> 673],
                        [ 'id' => 10721, 'name'=>"Saint-Ephrem-de-Tring", 'state_id'=> 673],
                        [ 'id' => 10722, 'name'=>"Saint-Fabien", 'state_id'=> 673],
                        [ 'id' => 10723, 'name'=>"Saint-Felicien", 'state_id'=> 673],
                        [ 'id' => 10724, 'name'=>"Saint-Felix-de-Valois", 'state_id'=> 673],
                        [ 'id' => 10725, 'name'=>"Saint-Gabriel", 'state_id'=> 673],
                        [ 'id' => 10726, 'name'=>"Saint-Gedeon", 'state_id'=> 673],
                        [ 'id' => 10727, 'name'=>"Saint-Georges", 'state_id'=> 673],
                        [ 'id' => 10728, 'name'=>"Saint-Germain-de-Grantham", 'state_id'=> 673],
                        [ 'id' => 10729, 'name'=>"Saint-Gregoire", 'state_id'=> 673],
                        [ 'id' => 10730, 'name'=>"Saint-Henri-de-Levis", 'state_id'=> 673],
                        [ 'id' => 10731, 'name'=>"Saint-Honore", 'state_id'=> 673],
                        [ 'id' => 10732, 'name'=>"Saint-Hyacinthe", 'state_id'=> 673],
                        [ 'id' => 10733, 'name'=>"Saint-Jacques", 'state_id'=> 673],
                        [ 'id' => 10734, 'name'=>"Saint-Jean-Port-Joli", 'state_id'=> 673],
                        [ 'id' => 10735, 'name'=>"Saint-Jean-de-Dieu", 'state_id'=> 673],
                        [ 'id' => 10736, 'name'=>"Saint-Jean-sur-Richelieu", 'state_id'=> 673],
                        [ 'id' => 10737, 'name'=>"Saint-Jerome", 'state_id'=> 673],
                        [ 'id' => 10738, 'name'=>"Saint-Josephe-de-Beauce", 'state_id'=> 673],
                        [ 'id' => 10739, 'name'=>"Saint-Josephe-de-Lanoraie", 'state_id'=> 673],
                        [ 'id' => 10740, 'name'=>"Saint-Josephe-de-la-Riviere-Bl", 'state_id'=> 673],
                        [ 'id' => 10741, 'name'=>"Saint-Jovite", 'state_id'=> 673],
                        [ 'id' => 10742, 'name'=>"Saint-Laurent", 'state_id'=> 673],
                        [ 'id' => 10743, 'name'=>"Saint-Liboire", 'state_id'=> 673],
                        [ 'id' => 10744, 'name'=>"Saint-Marc-des-Carrieres", 'state_id'=> 673],
                        [ 'id' => 10745, 'name'=>"Saint-Martin", 'state_id'=> 673],
                        [ 'id' => 10746, 'name'=>"Saint-Michel-des-Saints", 'state_id'=> 673],
                        [ 'id' => 10747, 'name'=>"Saint-Pacome", 'state_id'=> 673],
                        [ 'id' => 10748, 'name'=>"Saint-Pascal", 'state_id'=> 673],
                        [ 'id' => 10749, 'name'=>"Saint-Pie", 'state_id'=> 673],
                        [ 'id' => 10750, 'name'=>"Saint-Prosper", 'state_id'=> 673],
                        [ 'id' => 10751, 'name'=>"Saint-Raphael", 'state_id'=> 673],
                        [ 'id' => 10752, 'name'=>"Saint-Raymond", 'state_id'=> 673],
                        [ 'id' => 10753, 'name'=>"Saint-Remi", 'state_id'=> 673],
                        [ 'id' => 10754, 'name'=>"Saint-Roch-de-l''Achigan", 'state_id'=> 673],
                        [ 'id' => 10755, 'name'=>"Saint-Sauveur-des-Monts", 'state_id'=> 673],
                        [ 'id' => 10756, 'name'=>"Saint-Tite", 'state_id'=> 673],
                        [ 'id' => 10757, 'name'=>"Sainte-Adele", 'state_id'=> 673],
                        [ 'id' => 10758, 'name'=>"Sainte-Agathe-des-Monts", 'state_id'=> 673],
                        [ 'id' => 10759, 'name'=>"Sainte-Anne-des-Monts", 'state_id'=> 673],
                        [ 'id' => 10760, 'name'=>"Sainte-Anne-des-Plaines", 'state_id'=> 673],
                        [ 'id' => 10761, 'name'=>"Sainte-Catherine", 'state_id'=> 673],
                        [ 'id' => 10762, 'name'=>"Sainte-Claire", 'state_id'=> 673],
                        [ 'id' => 10763, 'name'=>"Sainte-Julienne", 'state_id'=> 673],
                        [ 'id' => 10764, 'name'=>"Sainte-Justine", 'state_id'=> 673],
                        [ 'id' => 10765, 'name'=>"Sainte-Madeleine", 'state_id'=> 673],
                        [ 'id' => 10766, 'name'=>"Sainte-Marie", 'state_id'=> 673],
                        [ 'id' => 10767, 'name'=>"Sainte-Martine", 'state_id'=> 673],
                        [ 'id' => 10768, 'name'=>"Sainte-Sophie", 'state_id'=> 673],
                        [ 'id' => 10769, 'name'=>"Sainte-Thecle", 'state_id'=> 673],
                        [ 'id' => 10770, 'name'=>"Sainte-Therese", 'state_id'=> 673],
                        [ 'id' => 10771, 'name'=>"Salaberry-de-Valleyfield", 'state_id'=> 673],
                        [ 'id' => 10772, 'name'=>"Sayabec", 'state_id'=> 673],
                        [ 'id' => 10773, 'name'=>"Senneterre", 'state_id'=> 673],
                        [ 'id' => 10774, 'name'=>"Sept-Iles", 'state_id'=> 673],
                        [ 'id' => 10775, 'name'=>"Shawinigan", 'state_id'=> 673],
                        [ 'id' => 10776, 'name'=>"Shawville", 'state_id'=> 673],
                        [ 'id' => 10777, 'name'=>"Sherbrooke", 'state_id'=> 673],
                        [ 'id' => 10778, 'name'=>"Sorel", 'state_id'=> 673],
                        [ 'id' => 10779, 'name'=>"St Faustin", 'state_id'=> 673],
                        [ 'id' => 10780, 'name'=>"St. Hubert", 'state_id'=> 673],
                        [ 'id' => 10781, 'name'=>"St. Jean Chrysostome", 'state_id'=> 673],
                        [ 'id' => 10782, 'name'=>"Temiscaming", 'state_id'=> 673],
                        [ 'id' => 10783, 'name'=>"Terrebonne", 'state_id'=> 673],
                        [ 'id' => 10784, 'name'=>"Thetford Mines", 'state_id'=> 673],
                        [ 'id' => 10785, 'name'=>"Thurso", 'state_id'=> 673],
                        [ 'id' => 10786, 'name'=>"Trois-Pistoles", 'state_id'=> 673],
                        [ 'id' => 10787, 'name'=>"Trois-Rivieres", 'state_id'=> 673],
                        [ 'id' => 10788, 'name'=>"Val-David", 'state_id'=> 673],
                        [ 'id' => 10789, 'name'=>"Val-d''Or", 'state_id'=> 673],
                        [ 'id' => 10790, 'name'=>"Valcourt", 'state_id'=> 673],
                        [ 'id' => 10791, 'name'=>"Vallee-Jonction", 'state_id'=> 673],
                        [ 'id' => 10792, 'name'=>"Vaudreuil", 'state_id'=> 673],
                        [ 'id' => 10793, 'name'=>"Vercheres", 'state_id'=> 673],
                        [ 'id' => 10794, 'name'=>"Victoriaville", 'state_id'=> 673],
                        [ 'id' => 10795, 'name'=>"Ville-Marie", 'state_id'=> 673],
                        [ 'id' => 10796, 'name'=>"Warwick", 'state_id'=> 673],
                        [ 'id' => 10797, 'name'=>"Waterloo", 'state_id'=> 673],
                        [ 'id' => 10798, 'name'=>"Weedon Centre", 'state_id'=> 673],
                        [ 'id' => 10799, 'name'=>"Westmount", 'state_id'=> 673],
                        [ 'id' => 10800, 'name'=>"Wickham", 'state_id'=> 673],
                        [ 'id' => 10801, 'name'=>"Windsor", 'state_id'=> 673],
                        [ 'id' => 10802, 'name'=>"Yamachiche", 'state_id'=> 673],
                        [ 'id' => 10803, 'name'=>"Assiniboia", 'state_id'=> 674],
                        [ 'id' => 10804, 'name'=>"Biggar", 'state_id'=> 674],
                        [ 'id' => 10805, 'name'=>"Canora", 'state_id'=> 674],
                        [ 'id' => 10806, 'name'=>"Carlyle", 'state_id'=> 674],
                        [ 'id' => 10807, 'name'=>"Carnduff", 'state_id'=> 674],
                        [ 'id' => 10808, 'name'=>"Caronport", 'state_id'=> 674],
                        [ 'id' => 10809, 'name'=>"Carrot", 'state_id'=> 674],
                        [ 'id' => 10810, 'name'=>"Dalmeny", 'state_id'=> 674],
                        [ 'id' => 10811, 'name'=>"Davidson", 'state_id'=> 674],
                        [ 'id' => 10812, 'name'=>"Esterhazy", 'state_id'=> 674],
                        [ 'id' => 10813, 'name'=>"Estevan", 'state_id'=> 674],
                        [ 'id' => 10814, 'name'=>"Eston", 'state_id'=> 674],
                        [ 'id' => 10815, 'name'=>"Foam Lake", 'state_id'=> 674],
                        [ 'id' => 10816, 'name'=>"Fort Qu''Appelle", 'state_id'=> 674],
                        [ 'id' => 10817, 'name'=>"Gravelbourg", 'state_id'=> 674],
                        [ 'id' => 10818, 'name'=>"Grenfell", 'state_id'=> 674],
                        [ 'id' => 10819, 'name'=>"Gull Lake", 'state_id'=> 674],
                        [ 'id' => 10820, 'name'=>"Hudson Bay", 'state_id'=> 674],
                        [ 'id' => 10821, 'name'=>"Humboldt", 'state_id'=> 674],
                        [ 'id' => 10822, 'name'=>"Indian Head", 'state_id'=> 674],
                        [ 'id' => 10823, 'name'=>"Kamsack", 'state_id'=> 674],
                        [ 'id' => 10824, 'name'=>"Kelvington", 'state_id'=> 674],
                        [ 'id' => 10825, 'name'=>"Kerrobert", 'state_id'=> 674],
                        [ 'id' => 10826, 'name'=>"Kindersley", 'state_id'=> 674],
                        [ 'id' => 10827, 'name'=>"Kipling", 'state_id'=> 674],
                        [ 'id' => 10828, 'name'=>"La Ronge", 'state_id'=> 674],
                        [ 'id' => 10829, 'name'=>"Langenburg", 'state_id'=> 674],
                        [ 'id' => 10830, 'name'=>"Langham", 'state_id'=> 674],
                        [ 'id' => 10831, 'name'=>"Lanigan", 'state_id'=> 674],
                        [ 'id' => 10832, 'name'=>"Lloydminster", 'state_id'=> 674],
                        [ 'id' => 10833, 'name'=>"Lumsden", 'state_id'=> 674],
                        [ 'id' => 10834, 'name'=>"Macklin", 'state_id'=> 674],
                        [ 'id' => 10835, 'name'=>"Maple Creek", 'state_id'=> 674],
                        [ 'id' => 10836, 'name'=>"Martensville", 'state_id'=> 674],
                        [ 'id' => 10837, 'name'=>"Meadow Lake", 'state_id'=> 674],
                        [ 'id' => 10838, 'name'=>"Melfort", 'state_id'=> 674],
                        [ 'id' => 10839, 'name'=>"Melville", 'state_id'=> 674],
                        [ 'id' => 10840, 'name'=>"Moose Jaw", 'state_id'=> 674],
                        [ 'id' => 10841, 'name'=>"Moosomin", 'state_id'=> 674],
                        [ 'id' => 10842, 'name'=>"Nipawin", 'state_id'=> 674],
                        [ 'id' => 10843, 'name'=>"North Battleford", 'state_id'=> 674],
                        [ 'id' => 10844, 'name'=>"Outlook", 'state_id'=> 674],
                        [ 'id' => 10845, 'name'=>"Oxbow", 'state_id'=> 674],
                        [ 'id' => 10846, 'name'=>"Pilot Butte", 'state_id'=> 674],
                        [ 'id' => 10847, 'name'=>"Preeceville", 'state_id'=> 674],
                        [ 'id' => 10848, 'name'=>"Prince Albert", 'state_id'=> 674],
                        [ 'id' => 10849, 'name'=>"Regina", 'state_id'=> 674],
                        [ 'id' => 10850, 'name'=>"Rosetown", 'state_id'=> 674],
                        [ 'id' => 10851, 'name'=>"Rosthem", 'state_id'=> 674],
                        [ 'id' => 10852, 'name'=>"Saskatoon", 'state_id'=> 674],
                        [ 'id' => 10853, 'name'=>"Shaunavon", 'state_id'=> 674],
                        [ 'id' => 10854, 'name'=>"Shellbrook", 'state_id'=> 674],
                        [ 'id' => 10855, 'name'=>"Swift Current", 'state_id'=> 674],
                        [ 'id' => 10856, 'name'=>"Tisdale", 'state_id'=> 674],
                        [ 'id' => 10857, 'name'=>"Unity", 'state_id'=> 674],
                        [ 'id' => 10858, 'name'=>"Wadena", 'state_id'=> 674],
                        [ 'id' => 10859, 'name'=>"Warman", 'state_id'=> 674],
                        [ 'id' => 10860, 'name'=>"Watrous", 'state_id'=> 674],
                        [ 'id' => 10861, 'name'=>"Weyburn", 'state_id'=> 674],
                        [ 'id' => 10862, 'name'=>"White City", 'state_id'=> 674],
                        [ 'id' => 10863, 'name'=>"Wilkie", 'state_id'=> 674],
                        [ 'id' => 10864, 'name'=>"Wynyard", 'state_id'=> 674],
                        [ 'id' => 10865, 'name'=>"Yorkton", 'state_id'=> 674],
                        [ 'id' => 10866, 'name'=>"Haines Junction", 'state_id'=> 675],
                        [ 'id' => 10867, 'name'=>"Mayo", 'state_id'=> 675],
                        [ 'id' => 10868, 'name'=>"Whitehorse", 'state_id'=> 675],
                        [ 'id' => 10869, 'name'=>"Sal Rei", 'state_id'=> 676],
                        [ 'id' => 10870, 'name'=>"Nova Sintra", 'state_id'=> 677],
                        [ 'id' => 10871, 'name'=>"Mosteiros", 'state_id'=> 678],
                        [ 'id' => 10872, 'name'=>"Sao Filipe", 'state_id'=> 678],
                        [ 'id' => 10873, 'name'=>"Vila do Maio", 'state_id'=> 679],
                        [ 'id' => 10874, 'name'=>"Santa Maria", 'state_id'=> 680],
                        [ 'id' => 10875, 'name'=>"Ndele", 'state_id'=> 686],
                        [ 'id' => 10876, 'name'=>"Bangui", 'state_id'=> 687],
                        [ 'id' => 10877, 'name'=>"Alindao", 'state_id'=> 688],
                        [ 'id' => 10878, 'name'=>"Kembe", 'state_id'=> 688],
                        [ 'id' => 10879, 'name'=>"Mobaye", 'state_id'=> 688],
                        [ 'id' => 10880, 'name'=>"Obo", 'state_id'=> 689],
                        [ 'id' => 10881, 'name'=>"Zemio", 'state_id'=> 689],
                        [ 'id' => 10882, 'name'=>"Bria", 'state_id'=> 690],
                        [ 'id' => 10883, 'name'=>"Ouadda", 'state_id'=> 690],
                        [ 'id' => 10884, 'name'=>"Dekoa", 'state_id'=> 691],
                        [ 'id' => 10885, 'name'=>"Sibut", 'state_id'=> 691],
                        [ 'id' => 10886, 'name'=>"Boda", 'state_id'=> 692],
                        [ 'id' => 10887, 'name'=>"Mbaiki", 'state_id'=> 692],
                        [ 'id' => 10888, 'name'=>"Mongoumba", 'state_id'=> 692],
                        [ 'id' => 10889, 'name'=>"Berberati", 'state_id'=> 693],
                        [ 'id' => 10890, 'name'=>"Carnot", 'state_id'=> 693],
                        [ 'id' => 10891, 'name'=>"Gamboula", 'state_id'=> 693],
                        [ 'id' => 10892, 'name'=>"Bangassou", 'state_id'=> 694],
                        [ 'id' => 10893, 'name'=>"Gambo", 'state_id'=> 694],
                        [ 'id' => 10894, 'name'=>"Ouango", 'state_id'=> 694],
                        [ 'id' => 10895, 'name'=>"Rafai", 'state_id'=> 694],
                        [ 'id' => 10896, 'name'=>"Kaga-Bandoro", 'state_id'=> 695],
                        [ 'id' => 10897, 'name'=>"Baboua", 'state_id'=> 696],
                        [ 'id' => 10898, 'name'=>"Baoro", 'state_id'=> 696],
                        [ 'id' => 10899, 'name'=>"Bouar", 'state_id'=> 696],
                        [ 'id' => 10900, 'name'=>"Bambari", 'state_id'=> 698],
                        [ 'id' => 10901, 'name'=>"Grimari", 'state_id'=> 698],
                        [ 'id' => 10902, 'name'=>"Ippy", 'state_id'=> 698],
                        [ 'id' => 10903, 'name'=>"Kouango", 'state_id'=> 698],
                        [ 'id' => 10904, 'name'=>"Batangafo", 'state_id'=> 699],
                        [ 'id' => 10905, 'name'=>"Bossangoa", 'state_id'=> 699],
                        [ 'id' => 10906, 'name'=>"Bouca", 'state_id'=> 699],
                        [ 'id' => 10907, 'name'=>"Kabo", 'state_id'=> 699],
                        [ 'id' => 10908, 'name'=>"Bocaranga", 'state_id'=> 700],
                        [ 'id' => 10909, 'name'=>"Bozoum", 'state_id'=> 700],
                        [ 'id' => 10910, 'name'=>"Paoua", 'state_id'=> 700],
                        [ 'id' => 10911, 'name'=>"Nola", 'state_id'=> 701],
                        [ 'id' => 10912, 'name'=>"Birao", 'state_id'=> 702],
                        [ 'id' => 10913, 'name'=>"Ati", 'state_id'=> 703],
                        [ 'id' => 10914, 'name'=>"Oum Hadjer", 'state_id'=> 703],
                        [ 'id' => 10915, 'name'=>"Biltine", 'state_id'=> 704],
                        [ 'id' => 10916, 'name'=>"Aouzou", 'state_id'=> 705],
                        [ 'id' => 10917, 'name'=>"Bardai", 'state_id'=> 705],
                        [ 'id' => 10918, 'name'=>"Fada", 'state_id'=> 705],
                        [ 'id' => 10919, 'name'=>"Faya", 'state_id'=> 705],
                        [ 'id' => 10920, 'name'=>"Bokoro", 'state_id'=> 706],
                        [ 'id' => 10921, 'name'=>"Bousso", 'state_id'=> 706],
                        [ 'id' => 10922, 'name'=>"Dourbali", 'state_id'=> 706],
                        [ 'id' => 10923, 'name'=>"Massaguet", 'state_id'=> 706],
                        [ 'id' => 10924, 'name'=>"Massakory", 'state_id'=> 706],
                        [ 'id' => 10925, 'name'=>"Massenya", 'state_id'=> 706],
                        [ 'id' => 10926, 'name'=>"N''Djamena", 'state_id'=> 706],
                        [ 'id' => 10927, 'name'=>"Ngama", 'state_id'=> 706],
                        [ 'id' => 10928, 'name'=>"Bitkine", 'state_id'=> 707],
                        [ 'id' => 10929, 'name'=>"Melfi", 'state_id'=> 707],
                        [ 'id' => 10930, 'name'=>"Mongo", 'state_id'=> 707],
                        [ 'id' => 10931, 'name'=>"Mao", 'state_id'=> 708],
                        [ 'id' => 10932, 'name'=>"Moussoro", 'state_id'=> 708],
                        [ 'id' => 10933, 'name'=>"Rig-Rig", 'state_id'=> 708],
                        [ 'id' => 10934, 'name'=>"Bol", 'state_id'=> 709],
                        [ 'id' => 10935, 'name'=>"Bongor", 'state_id'=> 712],
                        [ 'id' => 10936, 'name'=>"Fianga", 'state_id'=> 712],
                        [ 'id' => 10937, 'name'=>"Gounou Gaya", 'state_id'=> 712],
                        [ 'id' => 10938, 'name'=>"Guelengdeng", 'state_id'=> 712],
                        [ 'id' => 10939, 'name'=>"Lere", 'state_id'=> 712],
                        [ 'id' => 10940, 'name'=>"Pala", 'state_id'=> 712],
                        [ 'id' => 10941, 'name'=>"Goundi", 'state_id'=> 713],
                        [ 'id' => 10942, 'name'=>"Koumra", 'state_id'=> 713],
                        [ 'id' => 10943, 'name'=>"Kyabe", 'state_id'=> 713],
                        [ 'id' => 10944, 'name'=>"Moissala", 'state_id'=> 713],
                        [ 'id' => 10945, 'name'=>"Sarh", 'state_id'=> 713],
                        [ 'id' => 10946, 'name'=>"Abeche", 'state_id'=> 714],
                        [ 'id' => 10947, 'name'=>"Adre", 'state_id'=> 714],
                        [ 'id' => 10948, 'name'=>"Am Dam", 'state_id'=> 714],
                        [ 'id' => 10949, 'name'=>"Abou Deia", 'state_id'=> 715],
                        [ 'id' => 10950, 'name'=>"Am Timan", 'state_id'=> 715],
                        [ 'id' => 10951, 'name'=>"Mangueigne", 'state_id'=> 715],
                        [ 'id' => 10952, 'name'=>"Benoy", 'state_id'=> 716],
                        [ 'id' => 10953, 'name'=>"Bere", 'state_id'=> 716],
                        [ 'id' => 10954, 'name'=>"Kelo", 'state_id'=> 716],
                        [ 'id' => 10955, 'name'=>"Lai", 'state_id'=> 716],
                        [ 'id' => 10956, 'name'=>"Aisen", 'state_id'=> 717],
                        [ 'id' => 10957, 'name'=>"Chile Chico", 'state_id'=> 717],
                        [ 'id' => 10958, 'name'=>"Cisnes", 'state_id'=> 717],
                        [ 'id' => 10959, 'name'=>"Cochrane", 'state_id'=> 717],
                        [ 'id' => 10960, 'name'=>"Coihaique", 'state_id'=> 717],
                        [ 'id' => 10961, 'name'=>"Guaitecas", 'state_id'=> 717],
                        [ 'id' => 10962, 'name'=>"Lago Verde", 'state_id'=> 717],
                        [ 'id' => 10963, 'name'=>"O''Higgins", 'state_id'=> 717],
                        [ 'id' => 10964, 'name'=>"Rio Ibanez", 'state_id'=> 717],
                        [ 'id' => 10965, 'name'=>"Tortel", 'state_id'=> 717],
                        [ 'id' => 10966, 'name'=>"Antofagasta", 'state_id'=> 718],
                        [ 'id' => 10967, 'name'=>"Calama", 'state_id'=> 718],
                        [ 'id' => 10968, 'name'=>"Maria Elena", 'state_id'=> 718],
                        [ 'id' => 10969, 'name'=>"Mejilones", 'state_id'=> 718],
                        [ 'id' => 10970, 'name'=>"Ollague", 'state_id'=> 718],
                        [ 'id' => 10971, 'name'=>"San Pedro de Atacama", 'state_id'=> 718],
                        [ 'id' => 10972, 'name'=>"Sierra Gorda", 'state_id'=> 718],
                        [ 'id' => 10973, 'name'=>"Taltal", 'state_id'=> 718],
                        [ 'id' => 10974, 'name'=>"Tocopilla", 'state_id'=> 718],
                        [ 'id' => 10975, 'name'=>"Angol", 'state_id'=> 719],
                        [ 'id' => 10976, 'name'=>"Carahue", 'state_id'=> 719],
                        [ 'id' => 10977, 'name'=>"Collipulli", 'state_id'=> 719],
                        [ 'id' => 10978, 'name'=>"Cunco", 'state_id'=> 719],
                        [ 'id' => 10979, 'name'=>"Curacautin", 'state_id'=> 719],
                        [ 'id' => 10980, 'name'=>"Curarrehue", 'state_id'=> 719],
                        [ 'id' => 10981, 'name'=>"Ercilla", 'state_id'=> 719],
                        [ 'id' => 10982, 'name'=>"Freire", 'state_id'=> 719],
                        [ 'id' => 10983, 'name'=>"Galvarino", 'state_id'=> 719],
                        [ 'id' => 10984, 'name'=>"Gorbea", 'state_id'=> 719]

        ];
 
        \DB::table('cities')->insert($cities);
    }

}     